linters-settings:
  wrapcheck:
    ignoreSigs:
    - status.Error(
    - .Errorf(
    - errors.New(
    - errors.Unwrap(
    - errors.Join(
    - .Wrap(
    - .Wrapf(
    - .WithMessage(
    - .WithMessagef(
    - .WithStack(
  exhaustruct:
    exclude:
      - "http.Server"
  varnamelen:
    ignore-names:
      - err
      - ok
      - md
  gomoddirectives:
    list:
      - "github.com/oauth2-proxy/mockoidc"

linters:
  enable-all: true
  disable:
    - interfacer
    - maligned
    - deadcode
    - nosnakecase
    - varcheck
    - ifshort
    - structcheck
    - golint
    - scopelint
    - exhaustivestruct
    - structcheck
    - testpackage # I don't think we should have tests in a separate package
    - paralleltest
    - exhaustruct # Defaults are there for a reason...
    - gci # can be enabled after this is fixed: https://github.com/golangci/golangci-lint/issues/1490
    - gomoddirectives # Couldn't figure out how to allow the mockoidc import
    - goimports
    - importas
    - ireturn