codecov:
  ci:
    - "github.com"

coverage:
  precision: 0         # how many decimal places to display in the UI: 0 <= value <= 4
  round: down          # how coverage is rounded: down/up/nearest
  range: 70...90      # custom range of coverage colors from red -> yellow -> green

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        target: 80%            # specify the target coverage for each commit status

    patch:                     # pull requests only: this commit status will measure the
      # entire pull requests Coverage Diff. Checking if the lines
      # adjusted are covered at least X%.
      default:
        target: 75%              # specify the target "X%" coverage to hit
        branches: null           # -> see "branch patterns" below
        if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
        # options: success, error, failure
        if_not_found: success
        if_ci_failed: error

fixes:
  - "github.com/unsafesystems/cachaca/::"

ignore:
  - ".github/workflows"
  - ".github"