.PHONY: all

all: housekeeping test coverage

housekeeping:
	go fmt ./...
	go vet ./...
	golangci-lint run --fix ./...

test:
	go test -v ./...

coverage:
	go test --cover -coverprofile=coverage.cov ./...
	go tool cover -func coverage.cov
