on: [push, pull_request]
name: coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: run coverage
        run: go test --cover -covermode=set -coverprofile=coverage.txt -coverpkg=$(go list ./...) ./...
      - name: upload coverage
        uses: codecov/codecov-action@v3