on:
  pull_request:
  push:
    branches:
      - master
      - main
name: coverage
jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - name: run coverage
        run: go test --cover -covermode=set -coverprofile=coverage.txt -coverpkg=$(go list ./...) ./...
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt